---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true    
    checks:
      no-console:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "**.js"
exclude_paths:
  - node_modules/
  - build/
